version: '3.1'

services:

  laravel:
    build: .docker/php
    container_name: lara
    ports: 
      - "8000:80"
    volumes: 
      - ./lara:/var/www
    networks:
      - app    
  # web:
  #   build: .docker/react
  #   container_name: web
  #   ports: 
  #     - "3000:3000"
  #   volumes: 
  #     - ./react:/var/www/html

  db:
    build: .docker/mysql
    container_name: db
    restart: always
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment: 
      MYSQL_ROOT_PASSWORD: A_1234567
      MYSQL_DATABASE: laravel
    ports: 
      - "3307:3306"
    networks:
      - app      

  phpmyadmin: 
    image: phpmyadmin
    container_name: myadmin
    restart: always
    ports:
      - 8080:80
    networks:
      - app    

networks:
  app:
    driver: bridge